services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: elasticsearch2
    environment:
      - "discovery.type=single-node"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    
  streamlit:
    image: python:3.10.0 
    container_name: my_streamlit_app
    working_dir: /app
    volumes:
      - <INSERT FULL WORKING DIR HERE>:/app
    ports:
      - "8501:8501"  
    command: sh -c "pip install --upgrade -r requirements.txt && python index.py && streamlit run main.py"  
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local